<?php
namespace App\Controllers;
use App\Core\Controller;
use App\Models\Mahasiswa;
use App\Models\MahasiswaRepository;
use InvalidArgumentException;
class MahasiswaController extends Controller
{
    public function __construct(private MahasiswaRepository $repo) {}
    public function index(): void { $key=trim($_GET['keyword']??''); echo '<div class="d-flex justify-content-between mb-3"><h2>Mahasiswa</h2><a class="btn btn-primary" href="'.$this->url('/mahasiswa/create').'">Tambah</a></div><form class="input-group mb-3"><input name="keyword" value="'.htmlspecialchars($key).'" class="form-control" placeholder="Cari nama atau NIM"><button class="btn btn-outline-secondary">Cari</button></form><table class="table table-striped"><thead><tr><th>NIM</th><th>Nama</th><th>Email</th><th>Prodi</th><th>Status</th><th></th></tr></thead><tbody>'; foreach($this->repo->all($key) as $d){$m=Mahasiswa::fromArray($d);$id=$m->getId();echo '<tr><td>'.htmlspecialchars($m->getNim()).'</td><td>'.htmlspecialchars($m->getNama()).'</td><td>'.htmlspecialchars($m->getEmail()).'</td><td>'.htmlspecialchars($d['prodi_nama']).'</td><td>'.htmlspecialchars($m->getStatus()).'</td><td><a class="btn btn-sm btn-warning" href="'.$this->url('/mahasiswa/edit?id='.$id).'">Edit</a> <form class="d-inline" method="post" action="'.$this->url('/mahasiswa/delete?id='.$id).'" onsubmit="return confirm(\'Hapus data ini?\')"><button class="btn btn-sm btn-danger">Hapus</button></form></td></tr>'; } echo '</tbody></table>'; }
    public function create(): void { $this->form('Tambah Mahasiswa','/mahasiswa/store',['nim'=>'','nama'=>'','email'=>'','prodi_id'=>0,'angkatan'=>date('Y'),'status'=>'aktif']); }
    public function edit(): void { $d=$this->repo->find((int)($_GET['id']??0));if(!$d){http_response_code(404);echo 'Data mahasiswa tidak ditemukan.';return;}$this->form('Ubah Mahasiswa','/mahasiswa/update?id='.(int)$d['id'],$d); }
    private function form(string $title,string $action,array $d): void { echo '<h2>'.$title.'</h2><form method="post" action="'.$this->url($action).'"><div class="mb-2"><label>NIM</label><input class="form-control" name="nim" required value="'.htmlspecialchars($d['nim']).'"></div><div class="mb-2"><label>Nama</label><input class="form-control" name="nama" required value="'.htmlspecialchars($d['nama']).'"></div><div class="mb-2"><label>Email</label><input class="form-control" type="email" name="email" required value="'.htmlspecialchars($d['email']).'"></div><div class="mb-2"><label>Prodi</label><select class="form-select" name="prodi_id" required><option value="">-- Pilih Prodi --</option>';foreach($this->repo->prodiOptions() as $p){$s=(int)$d['prodi_id']===(int)$p['id']?' selected':'';echo '<option value="'.$p['id'].'"'.$s.'>'.htmlspecialchars($p['nama']).'</option>';}echo '</select></div><div class="mb-2"><label>Angkatan</label><input class="form-control" type="number" name="angkatan" required value="'.htmlspecialchars((string)$d['angkatan']).'"></div><div class="mb-3"><label>Status</label><select class="form-select" name="status">';foreach(['aktif','cuti','lulus'] as $status){$s=$d['status']===$status?' selected':'';echo '<option'.$s.'>'. $status .'</option>';}echo '</select></div><button class="btn btn-primary">Simpan</button> <a class="btn btn-secondary" href="'.$this->url('/mahasiswa').'">Batal</a></form>'; }
    public function store(): void {$this->save(null);} public function update(): void {$this->save((int)($_GET['id']??0));}
    private function save(?int $id): void { try{$m=new Mahasiswa((string)($_POST['nim']??''),(string)($_POST['nama']??''),(string)($_POST['email']??''),(int)($_POST['prodi_id']??0),(int)($_POST['angkatan']??0),(string)($_POST['status']??'aktif'),$id);$id?$this->repo->update($m):$this->repo->create($m);$this->redirect('/mahasiswa');}catch(InvalidArgumentException $e){echo '<div class="alert alert-danger">'.htmlspecialchars($e->getMessage()).'</div>';}}
    public function delete(): void {$this->repo->delete((int)($_GET['id']??0));$this->redirect('/mahasiswa');}
}
