<?php
namespace App\Controllers;
use App\Core\Controller;use App\Models\MatakuliahRepository;use App\Models\ProdiRepository;
class MatakuliahController extends Controller
{public function __construct(private MatakuliahRepository $repo,private ProdiRepository $prodi){}
 public function index():void{echo '<div class="d-flex justify-content-between mb-3"><h2>Mata Kuliah</h2><a class="btn btn-primary" href="'.$this->url('/matakuliah/create').'">Tambah</a></div><table class="table"><tr><th>Kode</th><th>Nama</th><th>SKS</th><th>Prodi</th><th></th></tr>';foreach($this->repo->all()as$d){$id=(int)$d['id'];echo '<tr><td>'.htmlspecialchars($d['kode']).'</td><td>'.htmlspecialchars($d['nama']).'</td><td>'.$d['sks'].'</td><td>'.htmlspecialchars($d['prodi_nama']).'</td><td><a class="btn btn-sm btn-warning" href="'.$this->url('/matakuliah/edit?id='.$id).'">Edit</a> <form class="d-inline" method="post" action="'.$this->url('/matakuliah/delete?id='.$id).'" onsubmit="return confirm(\'Hapus data ini?\')"><button class="btn btn-sm btn-danger">Hapus</button></form></td></tr>';}echo '</table>';}
 public function create():void{$this->form('Tambah Mata Kuliah','/matakuliah/store',['kode'=>'','nama'=>'','sks'=>0,'prodi_id'=>0]);}public function edit():void{$d=$this->repo->find((int)($_GET['id']??0));$d?$this->form('Ubah Mata Kuliah','/matakuliah/update?id='.$d['id'],$d):print('Data tidak ditemukan.');}
 private function form(string $t,string $a,array$d):void{echo '<h2>'.$t.'</h2><form method="post" action="'.$this->url($a).'"><div class="mb-2"><label>Kode</label><input class="form-control" name="kode" required value="'.htmlspecialchars($d['kode']).'"></div><div class="mb-2"><label>Nama</label><input class="form-control" name="nama" required value="'.htmlspecialchars($d['nama']).'"></div><div class="mb-2"><label>SKS</label><input class="form-control" type="number" name="sks" required value="'.$d['sks'].'"></div><div class="mb-3"><label>Prodi</label><select class="form-select" name="prodi_id">';foreach($this->prodi->all()as$p){$s=(int)$d['prodi_id']===(int)$p['id']?' selected':'';echo '<option value="'.$p['id'].'"'.$s.'>'.htmlspecialchars($p['nama']).'</option>';}echo '</select></div><button class="btn btn-primary">Simpan</button></form>';}
 public function store():void{$this->repo->save($_POST);$this->redirect('/matakuliah');}public function update():void{$this->repo->save($_POST,(int)($_GET['id']??0));$this->redirect('/matakuliah');}public function delete():void{$this->repo->delete((int)($_GET['id']??0));$this->redirect('/matakuliah');}}
